
sudo: false

branches:
  only:
    - master

language: go

go:
 - 1.8
 - tip

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet ./...
  - go test -race ./...
  - go test -cover ./...

matrix:
  allow_failures:
    - go: tip
